name: Taklif / Feature request
description: Yangi imkoniyat yoki yaxshilash taklifi
title: "[Taklif] "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Qanday muammoni hal qiladi?
      description: Qachon va nima uchun bu kerak bo'ladi.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Taklifingiz
      description: Qanday ishlashi kerak? Chizma yoki misol bo'lsa, yanada yaxshi.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Boshqa variantlar
      description: O'ylab ko'rgan boshqa yechimlar, agar bo'lsa.
  - type: checkboxes
    id: contribute
    attributes:
      label: Hissa
      options:
        - label: Buni o'zim qilib, PR yuborishga tayyorman
