#!/usr/bin/env python3
"""Ports the iOS emoji list (Keyboard/EmojiData.swift) to the Android keyboard.

Run from android/:  python3 tools/port_emoji.py   — rerun whenever the Swift list changes.
"""
import pathlib, re

root = pathlib.Path(__file__).resolve().parents[2]
swift = (root / "Keyboard/EmojiData.swift").read_text()
out = root / "android/app/src/main/java/com/ibrokhim/aikeyboard/ime/EmojiData.kt"

# SF Symbol names on iOS → a representative emoji for the Android category tab.
ICONS = {
    "face.smiling": "😀", "pawprint": "🐻", "fork.knife": "🍔", "soccerball": "⚽",
    "car": "🚗", "lightbulb": "💡", "heart": "❤️", "flag": "🏳️",
}

categories = re.findall(
    r'EmojiCategory\(title: "([^"]+)", symbol: "([^"]+)", emojis: split\("""\n(.*?)\n\s*"""\)\)', swift, re.S)
assert categories, "no categories found in EmojiData.swift"

blocks = []
for title, symbol, body in categories:
    lines = [" ".join(line.split()) for line in body.strip().splitlines() if line.strip()]
    assert not any("$" in line or '"""' in line for line in lines)
    joined = "\n".join("            " + line for line in lines)
    blocks.append(f'        EmojiCategory(\n            "{title}", "{ICONS[symbol]}",\n            split(\n                """\n{joined}\n                """,\n            ),\n        ),')

out.write_text(
    "// Generated by android/tools/port_emoji.py from Keyboard/EmojiData.swift — edit the Swift list and rerun.\n"
    "package com.ibrokhim.aikeyboard.ime\n\n"
    "data class EmojiCategory(val title: String, val icon: String, val emojis: List<String>)\n\n"
    "/** The iOS keyboard's curated emoji list, in the system keyboard's category order. */\n"
    "object EmojiData {\n"
    "    val categories: List<EmojiCategory> = listOf(\n"
    + "\n".join(blocks) + "\n"
    "    )\n\n"
    "    private fun split(text: String): List<String> = text.split(Regex(\"\\\\s+\")).filter { it.isNotEmpty() }\n"
    "}\n"
)
total = sum(len(body.split()) for _, _, body in categories)
print(f"wrote {out.relative_to(root)}: {len(categories)} categories, {total} emoji")
